production:
  cloud_name: <%= ENV["CLOUNDINARY_CLOUD_NAME"] %>
  api_key:  <%= ENV["CLOUNDINARY_API_KEY"] %>
  api_secret:  <%= ENV["CLOUNDINARY_API_SECRET"] %>

# heroku config:set CLOUDINARY_URL=cloudinary://my_key:my_secret@my_cloud_name
